import {
  index,
  int,
  mediumtext,
  mysqlEnum,
  mysqlTable,
  text,
  timestamp,
  varchar,
} from "drizzle-orm/mysql-core";
import {
  CHAPTER_STATUSES,
  DEFAULT_CHAPTER_STATUS,
} from "../shared/chapterPlanning";
import {
  GENERATION_STAGES,
  GENERATION_STATUSES,
} from "../shared/generationLifecycle";

/**
 * Core user table backing auth flow.
 * Extend this file with additional tables as your product grows.
 * Columns use camelCase to match both database fields and generated types.
 */
export const users = mysqlTable("users", {
  /**
   * Surrogate primary key. Auto-incremented numeric value managed by the database.
   * Use this for relations between tables.
   */
  id: int("id").autoincrement().primaryKey(),
  /** Stable identity key. The local profile uses `local-writer`. */
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * A long-form writing workspace. Projects group manuscript chapters and the
 * canon entries that may be supplied to a generation as explicit context.
 */
export const projects = mysqlTable("projects", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId")
    .notNull()
    .references(() => users.id),
  title: varchar("title", { length: 255 }).notNull(),
  premise: text("premise").notNull(),
  genre: varchar("genre", { length: 100 }),
  style: text("style"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Project = typeof projects.$inferSelect;
export type InsertProject = typeof projects.$inferInsert;

/**
 * Stories generated by the Z-88 Creative Engine
 */
export const stories = mysqlTable("stories", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").references(() => users.id),
  projectId: int("projectId").references(() => projects.id),
  title: varchar("title", { length: 255 }).notNull(),
  prompt: text("prompt").notNull(),
  content: mediumtext("content").notNull(),
  ritualId: varchar("ritualId", { length: 64 }).notNull().unique(),
  wordCount: int("wordCount").notNull(),
  qualityScore: int("qualityScore").notNull(), // stored as int (0-100) for simplicity
  ethicalApproval: int("ethicalApproval").notNull().default(1), // 1 = true, 0 = false
  ucfHarmony: int("ucfHarmony").notNull(), // stored as int (0-10000) for precision
  ucfPrana: int("ucfPrana").notNull(),
  ucfDrishti: int("ucfDrishti").notNull(),
  ucfKlesha: int("ucfKlesha").notNull(),
  ucfResilience: int("ucfResilience").notNull(),
  ucfZoom: int("ucfZoom").notNull(),
  agentContributions: text("agentContributions").notNull(), // JSON string of agent names
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  // Story series/chapters
  seriesId: varchar("seriesId", { length: 64 }),
  chapterNumber: int("chapterNumber"),
  previousChapterId: int("previousChapterId"),
  draftStatus: mysqlEnum("draftStatus", CHAPTER_STATUSES)
    .default(DEFAULT_CHAPTER_STATUS)
    .notNull(),
  synopsis: text("synopsis"),
  // Writer-controlled organization fields.
  collectionId: int("collectionId"),
  tags: text("tags"), // JSON array of tag strings
  isFavorite: int("isFavorite").notNull().default(0), // 1 = true, 0 = false
  deletedAt: timestamp("deletedAt"),
});

export type Story = typeof stories.$inferSelect;
export type InsertStory = typeof stories.$inferInsert;

/** Ordered, writer-authored beats used to guide an individual chapter. */
export const storyScenes = mysqlTable(
  "storyScenes",
  {
    id: int("id").autoincrement().primaryKey(),
    storyId: int("storyId")
      .notNull()
      .references(() => stories.id),
    projectId: int("projectId")
      .notNull()
      .references(() => projects.id),
    userId: int("userId")
      .notNull()
      .references(() => users.id),
    title: varchar("title", { length: 255 }).notNull(),
    summary: text("summary").notNull(),
    position: int("position").notNull(),
    pov: varchar("pov", { length: 255 }),
    location: varchar("location", { length: 255 }),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
    updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  },
  table => [
    index("storyScenes_story_position_idx").on(table.storyId, table.position),
    index("storyScenes_project_user_idx").on(table.projectId, table.userId),
  ]
);

export type StoryScene = typeof storyScenes.$inferSelect;
export type InsertStoryScene = typeof storyScenes.$inferInsert;

/**
 * Writer-authored source-of-truth notes. Activation keys make the context
 * selection deterministic and inspectable rather than silently sending an
 * entire project to a model.
 */
export const canonEntries = mysqlTable("canonEntries", {
  id: int("id").autoincrement().primaryKey(),
  projectId: int("projectId")
    .notNull()
    .references(() => projects.id),
  userId: int("userId")
    .notNull()
    .references(() => users.id),
  kind: mysqlEnum("kind", [
    "character",
    "location",
    "faction",
    "item",
    "lore",
  ]).notNull(),
  name: varchar("name", { length: 255 }).notNull(),
  content: text("content").notNull(),
  activationKeys: text("activationKeys").notNull(),
  alwaysInclude: int("alwaysInclude").notNull().default(0),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type CanonEntry = typeof canonEntries.$inferSelect;
export type InsertCanonEntry = typeof canonEntries.$inferInsert;

/** Recoverable manuscript snapshots created before every writer edit. */
export const storyRevisions = mysqlTable("storyRevisions", {
  id: int("id").autoincrement().primaryKey(),
  storyId: int("storyId")
    .notNull()
    .references(() => stories.id),
  userId: int("userId")
    .notNull()
    .references(() => users.id),
  title: varchar("title", { length: 255 }).notNull(),
  content: mediumtext("content").notNull(),
  reason: varchar("reason", { length: 64 }).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type StoryRevision = typeof storyRevisions.$inferSelect;
export type InsertStoryRevision = typeof storyRevisions.$inferInsert;

/**
 * Content-free lifecycle metadata for an asynchronous generation. Prompts and
 * draft text deliberately remain outside this table.
 */
export const generationJobs = mysqlTable(
  "generationJobs",
  {
    id: varchar("id", { length: 64 }).primaryKey(),
    userId: int("userId")
      .notNull()
      .references(() => users.id),
    projectId: int("projectId").references(() => projects.id),
    storyId: int("storyId").references(() => stories.id),
    ritualId: varchar("ritualId", { length: 64 }),
    mode: mysqlEnum("mode", ["demo", "provider"]).notNull(),
    status: mysqlEnum("status", GENERATION_STATUSES).notNull(),
    stage: mysqlEnum("stage", GENERATION_STAGES).notNull(),
    stageLabel: varchar("stageLabel", { length: 255 }).notNull(),
    progress: int("progress").notNull().default(0),
    cancelRequested: int("cancelRequested").notNull().default(0),
    errorMessage: varchar("errorMessage", { length: 512 }),
    createdAt: timestamp("createdAt").defaultNow().notNull(),
    updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
    completedAt: timestamp("completedAt"),
  },
  table => [
    index("generationJobs_user_status_created_idx").on(
      table.userId,
      table.status,
      table.createdAt
    ),
  ]
);

export type GenerationJob = typeof generationJobs.$inferSelect;
export type InsertGenerationJob = typeof generationJobs.$inferInsert;

/**
 * UCF state snapshots for visualization
 */
export const ucfStates = mysqlTable("ucfStates", {
  id: int("id").autoincrement().primaryKey(),
  ritualId: varchar("ritualId", { length: 64 }).notNull(),
  step: int("step").notNull(),
  harmony: int("harmony").notNull(),
  prana: int("prana").notNull(),
  drishti: int("drishti").notNull(),
  klesha: int("klesha").notNull(),
  resilience: int("resilience").notNull(),
  zoom: int("zoom").notNull(),
  timestamp: timestamp("timestamp").defaultNow().notNull(),
});

export type UcfState = typeof ucfStates.$inferSelect;
export type InsertUcfState = typeof ucfStates.$inferInsert;

/**
 * Agent activity logs
 */
export const agentLogs = mysqlTable("agentLogs", {
  id: int("id").autoincrement().primaryKey(),
  ritualId: varchar("ritualId", { length: 64 }).notNull(),
  agentName: varchar("agentName", { length: 64 }).notNull(),
  agentSymbol: varchar("agentSymbol", { length: 8 }).notNull(),
  role: varchar("role", { length: 128 }).notNull(),
  content: text("content").notNull(),
  timestamp: timestamp("timestamp").defaultNow().notNull(),
});

export type AgentLog = typeof agentLogs.$inferSelect;
export type InsertAgentLog = typeof agentLogs.$inferInsert;

/**
 * Story collections/folders
 */
export const collections = mysqlTable("collections", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId")
    .notNull()
    .references(() => users.id),
  name: varchar("name", { length: 255 }).notNull(),
  description: text("description"),
  color: varchar("color", { length: 7 }), // Hex color code
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Collection = typeof collections.$inferSelect;
export type InsertCollection = typeof collections.$inferInsert;
